import { createClient } from "@/lib/supabase/server";
import type { ContentItem } from "@/types/content";

function toContent(row: Record<string, unknown>): ContentItem {
  return { id: String(row.id), title: String(row.title || ""), body: String(row.body || ""), contentType: String(row.content_type || "General Post"), platform: String(row.platform || "X"), status: row.status as ContentItem["status"], tags: Array.isArray(row.tags) ? row.tags as string[] : [], createdAt: String(row.created_at), updatedAt: String(row.updated_at), scheduledAt: row.scheduled_at ? String(row.scheduled_at) : null };
}

export async function getContent() { const supabase = await createClient(); const { data, error } = await supabase.from("content").select("*").order("created_at", { ascending: false }); if (error) throw error; return (data || []).map(toContent); }
export async function createContent(userId: string, item: Omit<ContentItem, "id" | "createdAt" | "updatedAt">) { const supabase = await createClient(); const { data, error } = await supabase.from("content").insert({ user_id: userId, title: item.title, body: item.body, content_type: item.contentType, platform: item.platform, status: item.status, tags: item.tags, scheduled_at: item.scheduledAt }).select().single(); if (error) throw error; return toContent(data); }
export async function updateContent(userId: string, id: string, patch: Partial<ContentItem>) { const supabase = await createClient(); const update = { ...(patch.title === undefined ? {} : { title: patch.title }), ...(patch.body === undefined ? {} : { body: patch.body }), ...(patch.contentType === undefined ? {} : { content_type: patch.contentType }), ...(patch.platform === undefined ? {} : { platform: patch.platform }), ...(patch.status === undefined ? {} : { status: patch.status }), ...(patch.tags === undefined ? {} : { tags: patch.tags }), ...(patch.scheduledAt === undefined ? {} : { scheduled_at: patch.scheduledAt }), updated_at: new Date().toISOString() }; const { data, error } = await supabase.from("content").update(update).eq("id", id).eq("user_id", userId).select().single(); if (error) throw error; return toContent(data); }
export async function deleteContent(userId: string, id: string) { const supabase = await createClient(); const { error } = await supabase.from("content").delete().eq("id", id).eq("user_id", userId); if (error) throw error; }
