'use client';
import { useEffect, useState } from 'react';
import { AppShell } from '@/components/app-shell';
import { SettingsShell } from '@/components/settings-shell';
import { ApiClientError, api } from '@/lib/api';
import { Button, Card, EmptyState, PageHeader, Skeleton } from '@/components/ui';

type Billing={status:string;plan?:{code:string;name:string;monthlyPriceCents:number;entitlements:Array<{feature:string;limitValue:number|null}>}|null;currentPeriodEnd?:string|null}|null;
const plans=[{code:'FREE',name:'Free',price:'$0',description:'A practical starting point for every workspace.'},{code:'PRO',name:'Pro',price:'$19.99/month',description:'More room for content operations and AI.'},{code:'BUSINESS',name:'Business',price:'$49.99/month',description:'Business workflows, attribution, and higher limits.'}];
export default function BillingPage(){
 const [workspaceId,setWorkspaceId]=useState('');const [billing,setBilling]=useState<Billing>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState('');
 const load=()=>{const id=localStorage.getItem('contentra_workspace')??'';setWorkspaceId(id);if(!id){setLoading(false);return}setLoading(true);api<Billing>(`/api/v1/workspaces/${id}/billing`,{},id).then(setBilling).catch(e=>setError(e instanceof ApiClientError?e.message:'Billing could not be loaded.')).finally(()=>setLoading(false))};
 useEffect(load,[]);
 async function checkout(plan:'PRO'|'BUSINESS'){if(!workspaceId)return;setBusy(plan);setError('');try{const result=await api<{url:string}>(`/api/v1/workspaces/${workspaceId}/billing/checkout`,{method:'POST',body:JSON.stringify({plan})},workspaceId);window.location.assign(result.url)}catch(e){setError(e instanceof ApiClientError?e.message:'Checkout could not be started.')}finally{setBusy('')}}
 return <AppShell active="Settings"><SettingsShell active="billing"><PageHeader title="Billing" description="Plans and checkout use the current workspace subscription. Stripe is TEST/SANDBOX only."/>{error&&<p role="alert" style={{color:'var(--danger)'}}>{error}</p>}{loading?<div className="grid grid-3"><Skeleton className="skeleton-block"/><Skeleton className="skeleton-block"/><Skeleton className="skeleton-block"/></div>:<><Card><span className="eyebrow">Current plan</span><h2>{billing?.plan?.name??'Free'}</h2><p>{billing?.status?`Status: ${billing.status}`:'No subscription record yet; the workspace is on Free.'}{billing?.currentPeriodEnd&&` · Renews ${new Date(billing.currentPeriodEnd).toLocaleDateString()}`}</p>{billing?.plan?.entitlements?.length?<div className="section"><h3>Plan limits</h3>{billing.plan.entitlements.map(limit=><p key={limit.feature}>{limit.feature.replaceAll('_',' ')}: {limit.limitValue??'Included'}</p>)}</div>:null}</Card><div className="section grid grid-3">{plans.map(plan=><Card key={plan.code}><span className="eyebrow">{plan.code}</span><h2>{plan.name}</h2><h3>{plan.price}</h3><p>{plan.description}</p>{plan.code==='FREE'?<Button variant="secondary" disabled>Included</Button>:<Button onClick={()=>void checkout(plan.code as 'PRO'|'BUSINESS')} disabled={Boolean(busy)}>{busy===plan.code?'Opening checkout…':'Upgrade'}</Button>}</Card>)}</div>{!billing&&<div className="section"><EmptyState title="Stripe TEST checkout is unavailable" description="Plans remain visible. Add Stripe TEST credentials, TEST price IDs, and a TEST webhook signing secret to enable upgrades."/></div>}</>}</SettingsShell></AppShell>
}
