'use client';
import { useEffect, useState } from 'react';
import { AppShell } from '@/components/app-shell';
import { Button, Card, EmptyState, Metric, PageHeader, Badge, Skeleton } from '@/components/ui';
import { api, ApiClientError } from '@/lib/api';

type Opportunity={id:string;title:string;description:string;whyItMatters?:string|null;suggestedFormat?:string|null;suggestedPlatform?:string|null;relevanceScore?:number|null};
type ContentItem={id:string;title?:string|null;format:string;platform:string;status:string;updatedAt:string};
type HomeData={nba: {title:string;reason:string;type:string}|null; opportunities:Opportunity[]; recommendations:Array<{id:string;title:string;reason:string;priority:number}>; recentContent:ContentItem[]; upcomingCalendar:Array<{id:string;scheduledFor:string;status:string;platform?:string|null;content?:ContentItem|null}>; metrics:Array<{views?:number|null;reach?:number|null;followers?:number|null;engagementRate?:number|null}>};
function useWorkspace(){const [id,setId]=useState('');useEffect(()=>setId(localStorage.getItem('contentra_workspace')??''),[]);return id}
function fmt(n:number|undefined|null){return n==null?'—':new Intl.NumberFormat().format(n)}

export function Home(){
 const workspaceId=useWorkspace();
 const [data,setData]=useState<HomeData|null>(null);
 const [error,setError]=useState('');
 const load=()=>{if(!workspaceId)return;setData(null);setError('');api<HomeData>(`/api/v1/workspaces/${workspaceId}/home`,{},workspaceId).then(setData).catch(e=>setError(e instanceof ApiClientError?e.message:'Your brief could not be loaded.'))};
 useEffect(load,[workspaceId]);
 const latest=data?.metrics?.[0];
 return <AppShell active="Home"><PageHeader eyebrow="Today" title="Good to see you." description="Your business, content, and performance in one place." action={<Button href="/app/create">Create content</Button>}/>
  {error?<EmptyState title="We couldn't load your workspace" description={error} action={<Button onClick={load}>Retry</Button>}/>
   :data===null?<><div className="home-hero-skeleton"><Skeleton className="skeleton-block"/></div><div className="section grid grid-4">{[1,2,3,4].map(x=><Skeleton key={x} className="skeleton-block"/></div></>
   :<>
    <section className="home-brief"><div><span className="eyebrow">Next best action</span><h2>{data.nba?.title??'Your Contentra workspace is ready.'}</h2><p>{data.nba?.reason??'Use Create or Creatos to turn your business context into your next piece of content.'}</p></div><Button href={data.nba?'/creatos':'/app/create'}>{data.nba?'Act on it':'Start creating'}</Button></section>
    <div className="section home-metrics"><div className="metric-card"><span>Views</span><strong>{fmt(latest?.views)}</strong><small>Latest synced data</small></div><div className="metric-card"><span>Reach</span><strong>{fmt(latest?.reach)}</strong><small>Latest synced data</small></div><div className="metric-card"><span>Followers</span><strong>{fmt(latest?.followers)}</strong><small>Latest synced data</small></div><div className="metric-card"><span>Engagement</span><strong>{latest?.engagementRate==null?'—':`${(latest.engagementRate*100).toFixed(1)}%`}</strong><small>Latest synced data</small></div></div>
    <div className="section home-grid">
      <Card className="home-panel home-opportunities"><div className="panel-head"><div><span className="eyebrow">Intelligence</span><h3>Opportunities</h3></div><a className="text-btn" href="/creatos">Open Creatos</a></div>{data.opportunities.length?data.opportunities.slice(0,3).map(o=><div className="home-opportunity" key={o.id}><div><Badge>Opportunity</Badge><h4>{o.title}</h4><p>{o.whyItMatters??o.description}</p></div><Button href={`/app/create/custom?opportunity=${o.id}`}>Create</Button></div>):<EmptyState title="No opportunities yet" description="Contentra will surface ideas once enough workspace context and data are available."/>}</Card>
      <Card className="home-panel"><div className="panel-head"><div><span className="eyebrow">Performance</span><h3>What matters</h3></div><a className="text-btn" href="/app/analytics">Analytics</a></div>{data.recommendations.length?data.recommendations.slice(0,4).map(r=><div className="insight-row" key={r.id}><span className="insight-number">{r.priority}</span><div><strong>{r.title}</strong><p>{r.reason}</p></div></div>):<EmptyState title="Insights are building" description="More synced history will unlock performance recommendations."/>}</Card>
    </div>
    <div className="section home-grid">
      <Card className="home-panel"><div className="panel-head"><div><span className="eyebrow">Content</span><h3>Recent work</h3></div><a className="text-btn" href="/app/content">View all</a></div>{data.recentContent.length?data.recentContent.slice(0,5).map(c=><div className="content-row" key={c.id}><div className="content-thumb">{c.format.slice(0,1).toUpperCase()}</div><div><strong>{c.title??'Untitled content'}</strong><p>{c.platform} · {c.format}</p></div><Badge>{c.status}</Badge></div>):<EmptyState title="Nothing created yet" description="Start with Creatos or create something from scratch." action={<Button href="/app/create">Create</Button>}/>}</Card>
      <Card className="home-panel"><div className="panel-head"><div><span className="eyebrow">Execution</span><h3>Upcoming</h3></div><a className="text-btn" href="/app/calendar">Calendar</a></div>{data.upcomingCalendar.length?data.upcomingCalendar.slice(0,5).map(x=><div className="schedule-row" key={x.id}><div className="schedule-date"><b>{new Date(x.scheduledFor).getDate()}</b><small>{new Date(x.scheduledFor).toLocaleDateString(undefined,{month:'short'})}</small></div><div><strong>{x.content?.title??'Calendar item'}</strong><p>{x.platform??x.content?.platform??'Platform'} · {new Date(x.scheduledFor).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</p></div><Badge>{x.status}</Badge></div>):<EmptyState title="Nothing scheduled" description="Turn finished content into a publishing plan from Calendar." action={<Button href="/app/calendar">Open calendar</Button>}/>}</Card>
    </div>
   </>}
 </AppShell>;
}
export function Create(){const formats=['Slideshow','Wall of Text','Cutting Fruit','On a Walk','Netflix Documentary','Video Hook & Demo','Speaking Hook & Demo','Talking Head UGC','Green Screen Meme','Talking Head Green Screen','Product Spokesperson','Green Screen Mobile with App','Claymation','Lego','Talking Objects','Felt','Skeleton','Street Interview','Character Swap','Custom'];return <AppShell active="Create"><PageHeader title="Create new content" description="Pick a format to get started. You can switch anytime."/><Card className="ambient"><span className="eyebrow">Recommended for you</span><h2 style={{margin:'9px 0 5px'}}>Recommendation comes from Contentra intelligence</h2><p>No format is fabricated when your workspace has insufficient evidence.</p><Button href="/app/create/custom">Start creating</Button></Card><div className="section"><div className="section-title"><h2>Format library</h2><span className="muted">Reusable creation infrastructure</span></div><div className="grid grid-4">{formats.map(x=><Card className="format-card" key={x}><div><div className="format-preview">{x}</div><h3>{x}</h3><p>Reusable creation inputs with contextual intelligence.</p></div><Button href={`/app/create/${x.toLowerCase().replaceAll(' ','-')}`} variant="secondary">Start</Button></Card>)}</div></div></AppShell>}