'use client';
import Link from 'next/link';import { useState } from 'react';import { BarChart3, RefreshCw, Share2, Sparkles, TrendingUp } from 'lucide-react';import { Button } from '@/components/ui';import { api, ApiClientError } from '@/lib/api';
const features=[{t:'Create Better Content',d:'Generate content ideas, hooks, posts, scripts, and formats built around your brand and audience.',Icon:Sparkles},{t:'Discover What\u2019s Trending',d:'Find emerging trends and proven content opportunities before they pass you by.',Icon:TrendingUp},{t:'Remix What Works',d:'Turn proven content into new ideas tailored to your niche, brand, and audience.',Icon:RefreshCw},{t:'Publish Everywhere',d:'Plan, organize, and publish your content across your connected social platforms from one place.',Icon:Share2},{t:'Understand Your Growth',d:'Track your content performance and turn your analytics into clear next actions.',Icon:BarChart3}];
export default function Signup(){const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{await api('/api/v1/auth/signup',{method:'POST',body:JSON.stringify({email:d.get('email'),password:d.get('password'),name:d.get('name')})});location.href='/onboarding'}catch(err){setError(err instanceof ApiClientError?err.message:'Unable to create your account.')}finally{setBusy(false)}}
return <main className="auth-split">
<section className="auth-left"><Link href="/" className="auth-brand"><span className="brand-mark" aria-hidden="true" />Contentra</Link>
<div className="auth-left-copy"><h1>Grow your content 10x with Contentra</h1><p>The operating system for creators. Turn ideas into content, understand what's working, and know exactly what to create next.</p>
<div className="auth-features">{features.map(f=><div className="auth-feature" key={f.t}><span className="auth-feature-icon"><f.Icon size={16} aria-hidden="true"/></span><div><h3>{f.t}</h3><p>{f.d}</p></div></div>)}</div>
<p className="auth-claim">Your Content. Your Growth. One Operating System.</p></div></section>
<section className="auth-right"><div className="auth-right-card"><h1>Create your Contentra account</h1><p>Start building smarter content and growing your audience.</p>
<form className="form" onSubmit={submit}><label className="field"><span>Name</span><input name="name" required autoComplete="name" placeholder="Your name"/></label><label className="field"><span>Email address</span><input name="email" type="email" required autoComplete="email" placeholder="you@example.com"/></label><label className="field"><span>Password</span><input name="password" type="password" minLength={12} required autoComplete="new-password" placeholder="At least 12 characters"/></label>{error&&<div className="empty" style={{padding:12,color:'var(--danger)'}}>{error}</div>}<Button type="submit" disabled={busy}>{busy?'Creating account…':'Create account'}</Button></form>
<div className="auth-foot">Already have an account? <Link href="/login">Sign in</Link></div></div></section></main>}