'use client';
import Link from 'next/link';
import { ArrowRight, Command, Search, Sparkles, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api, ApiClientError } from '@/lib/api';

type Variant = 'primary' | 'secondary' | 'ghost' | 'danger';
export function Button({ children, href, variant = 'primary', type = 'button', onClick, disabled = false, ariaLabel }: { children: React.ReactNode; href?: string; variant?: Variant; type?: 'button' | 'submit'; onClick?: () => void; disabled?: boolean; ariaLabel?: string }) {
  const cls = `btn btn-${variant}`;
  if (href) return <Link className={cls} href={href} onClick={onClick} aria-label={ariaLabel}>{children}</Link>;
  return <button className={cls} type={type} onClick={onClick} disabled={disabled} aria-label={ariaLabel}>{children}</button>;
}
export function Card({ children, className = '', style }: { children: React.ReactNode; className?: string; style?: React.CSSProperties }) { return <section className={`card ${className}`} style={style}>{children}</section> }
export function Badge({ children }: { children: React.ReactNode }) { return <span className="badge">{children}</span> }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="empty"><div className="empty-icon"><Sparkles size={18} /></div><h3>{title}</h3><p>{description}</p>{action}</div> }
export function Skeleton({ className = '' }: { className?: string }) { return <div className={`skeleton ${className}`} aria-hidden="true" /> }
export function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <header className="page-header">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<div className="header-row"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div></header> }
export function Tabs({ items, active, onSelect, label }: { items: string[]; active: string; onSelect?: (item: string) => void; label?: string }) { return <nav className="tabs" aria-label={label}>{items.map(x => <button key={x} className={x === active ? 'active' : ''} onClick={() => onSelect?.(x)} aria-pressed={x === active}>{x}</button>)}</nav> }
export function Select({ label, name, value, onChange, children }: { label: string; name?: string; value?: string; onChange?: React.ChangeEventHandler<HTMLSelectElement>; children: React.ReactNode }) { return <label className="field"><span>{label}</span><select name={name} value={value} onChange={onChange}>{children}</select></label> }
export function TextInput({ label, name, value, onChange, placeholder, type = 'text', required }: { label: string; name?: string; value?: string; onChange?: React.ChangeEventHandler<HTMLInputElement>; placeholder?: string; type?: string; required?: boolean }) { return <label className="field"><span>{label}</span><input name={name} value={value} onChange={onChange} placeholder={placeholder} type={type} required={required} /></label> }
export function AIWidget() { const [open, setOpen] = useState(false); const [prompt, setPrompt] = useState(''); const [answer, setAnswer] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function ask(value = prompt) { const workspaceId = localStorage.getItem('contentra_workspace') ?? ''; if (!workspaceId) { setError('Select a workspace before using Contentra AI.'); return } if (!value.trim()) return; setLoading(true); setError(''); try { const result = await api<{ output: string }>(`/api/v1/workspaces/${workspaceId}/ai/actions`, { method: 'POST', body: JSON.stringify({ type: 'analyze_content', input: { prompt: value, context: location.pathname } }) }, workspaceId); setAnswer(result.output); setPrompt('') } catch (e) { setError(e instanceof ApiClientError ? e.message : 'Contentra AI could not complete that request.') } finally { setLoading(false) } } return <><button className="ai-fab" onClick={() => setOpen(!open)} aria-label="Open Contentra AI"><span className="ai-logo"><img src="/contentra-icon.svg" alt="" /></span><span>Contentra AI</span></button>{open && <div className="ai-panel card ai-glass-panel" role="dialog" aria-label="Contentra AI"><div className="ai-head"><div><Badge>Contentra AI</Badge><h3>Your intelligence layer</h3></div><button className="icon-btn" onClick={() => setOpen(false)} aria-label="Close AI"><X size={18} /></button></div><p className="muted">Ask about your content, opportunities, analytics, or what to create next.</p>{answer && <p>{answer}</p>}{error && <p role="alert">{error}</p>}<div className="ai-suggestions"><button onClick={() => void ask('What should I post today?')}>What should I post today?</button><button onClick={() => void ask('Why did my post perform well?')}>Why did my post perform well?</button><button onClick={() => void ask('Plan my week')}>Plan my week</button></div><div className="ai-input"><input aria-label="Ask Contentra AI" value={prompt} onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void ask() }} placeholder="Ask Contentra…" /><button aria-label="Send" className={loading ? 'loading' : ''} disabled={loading} onClick={() => void ask()}>{!loading && <ArrowRight size={16} />}</button></div></div>}</> }
export function SearchButton({ onClick }: { onClick?: () => void }) { return <button className="search-btn" onClick={onClick} aria-label="Search content" aria-keyshortcuts="Control+K"><Search size={16} /> Search <kbd><Command size={11} /> K</kbd></button> }
type ToastItem = { id: number; message: string; tone: 'success' | 'error' | 'info' };
const toastListeners = new Set<(t: ToastItem) => void>();
export function toast(message: string, tone: ToastItem['tone'] = 'info') { toastListeners.forEach(l => l({ id: Date.now() + Math.random(), message, tone })) }
export function Toaster() { const [toasts, setToasts] = useState<ToastItem[]>([]); useEffect(() => { const listen = (t: ToastItem) => { setToasts(cur => [...cur, t]); window.setTimeout(() => setToasts(cur => cur.filter(x => x.id !== t.id)), 3200) }; toastListeners.add(listen); return () => { toastListeners.delete(listen) } }, []); if (!toasts.length) return null; return <div className="toaster" aria-live="polite">{toasts.map(t => <div key={t.id} className={`toast toast-${t.tone}`} role="status">{t.message}</div>)}</div> }