import Link from "next/link";

const platforms = [["YT", "YouTube", "Channel analytics and audience signals."], ["X", "X", "Understand what earns attention in the feed."], ["TK", "TikTok", "Track video performance in one view."], ["IG", "Instagram", "Bring professional account insights together."]] as const;

export default function Home() {
  return <main className="public-page">
    <nav className="public-nav public-container" aria-label="Main navigation"><Link href="/" className="brand"><span className="brand-mark">C</span>Contentra</Link><div className="nav-links"><Link href="/pricing">Pricing</Link><Link href="/login">Sign in</Link><Link href="/signup" className="nav-cta">Get started <span aria-hidden="true">↗</span></Link></div></nav>
    <section className="hero public-container"><div className="hero-copy"><p className="eyebrow">The creator operating system</p><h1>Understand your content. <em>Create what works.</em></h1><p className="hero-lede">Connect your social accounts, understand your performance, and use actionable AI insights to make your next piece stronger.</p><div className="hero-actions"><Link href="/signup" className="button button-primary">Get started <span aria-hidden="true">↗</span></Link><Link href="/login" className="button button-secondary">Sign in</Link></div><p className="hero-note">Built for creators who want a clearer signal from every post.</p></div><div className="signal-board" aria-label="Contentra performance overview"><div className="board-top"><span>Performance signal</span><span className="live-dot">● Live view</span></div><div className="signal-number">+38.4% <small>vs last period</small></div><div className="signal-chart"><span style={{ height: "34%" }} /><span style={{ height: "47%" }} /><span style={{ height: "42%" }} /><span style={{ height: "59%" }} /><span style={{ height: "52%" }} /><span style={{ height: "76%" }} /><span style={{ height: "88%" }} /></div><div className="board-footer"><span>Reach</span><strong>24,860</strong><span className="accent-label">↑ 12.8%</span></div></div></section>
    <section className="platform-strip public-container"><div><p className="eyebrow">Connected platforms</p><h2>Your content, one clearer picture.</h2></div><div className="platform-grid">{platforms.map(([mark, name, detail]) => <div className="platform-item" key={name}><span className="platform-mark">{mark}</span><div><strong>{name}</strong><p>{detail}</p></div></div>)}</div></section>
    <section className="feature-section public-container"><div className="feature-intro"><p className="eyebrow">From data to direction</p><h2>Less dashboard noise. More useful decisions.</h2><p>Contentra gathers the signals that matter, then helps you decide what to keep, change, and try next.</p></div><div className="feature-list"><article><span>01</span><div><h3>See the signal</h3><p>Bring performance from your connected platforms into one focused analytics view.</p></div></article><article><span>02</span><div><h3>Ask your coach</h3><p>Use your real performance context to get practical recommendations from AI Coach.</p></div></article><article><span>03</span><div><h3>Make the next move</h3><p>Keep your ideas, analysis, and content workflow close to the insights behind them.</p></div></article></div></section>
    <section className="final-cta public-container"><div><p className="eyebrow">A better content loop</p><h2>Start with what your audience is already telling you.</h2></div><Link href="/signup" className="button button-primary">Create your workspace <span aria-hidden="true">↗</span></Link></section>
    <footer className="public-footer public-container"><span>© {new Date().getFullYear()} Contentra</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/pricing">Pricing</Link></div></footer>
  </main>;
}
