"use client";
import { useState } from "react";

type Plan = "FREE" | "CREATOR" | "PRO";
const plans: { name: Plan; price: string; limit: string; description: string }[] = [
  { name: "FREE", price: "$0", limit: "10 AI generations / month", description: "The essential creator workspace." },
  { name: "CREATOR", price: "$9.99", limit: "150 AI generations / month", description: "More room to create consistently." },
  { name: "PRO", price: "$19.99", limit: "1,000 AI generations / month", description: "A larger runway for serious output." },
];
export default function BillingPage({ currentPlan = "FREE", status = "active", renewal, paypalConfigured }: { currentPlan?: Plan; status?: string; renewal?: string | null; paypalConfigured: boolean }) {
  const [error, setError] = useState(""); const [loading, setLoading] = useState<Plan | "">(""); const [canceled, setCanceled] = useState(false);
  const checkout = async (plan: Plan) => { setLoading(plan); setError(""); const response = await fetch("/api/billing/paypal/create-subscription", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ plan }) }); const data = await response.json(); if (!response.ok) setError(data.error || "PayPal checkout is unavailable."); else if (data.url) window.location.assign(data.url); setLoading(""); };
  const cancel = async () => { setError(""); const response = await fetch("/api/billing/paypal/cancel-subscription", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason: "Requested by subscriber" }) }); const data = await response.json(); if (!response.ok) setError(data.error || "Cancellation is unavailable."); else { setCanceled(true); window.location.reload(); } };
  return <main className="min-h-screen bg-[var(--background)] px-5 py-8 sm:px-10"><div className="mx-auto max-w-5xl"><a href="/dashboard" className="text-sm text-[var(--purple-light)]">← Dashboard</a><h1 className="mt-10 text-3xl font-bold">Billing</h1><p className="mt-2 text-[var(--muted)]">Choose the amount of creative headroom you need.</p>{!paypalConfigured && <p className="mt-5 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4 text-sm text-[var(--muted)]">PayPal billing is not configured yet. Add the sandbox credentials and plan IDs to enable subscriptions.</p>}<section className="mt-8 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Current plan</p><div className="mt-2 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold">{currentPlan}</h2><p className="mt-1 text-sm text-[var(--muted)]">Status: {status}{renewal ? ` · Renews ${new Date(renewal).toLocaleDateString()}` : ""}</p></div>{currentPlan !== "FREE" && <button onClick={cancel} disabled={canceled} className="rounded-xl border border-[var(--border)] px-4 py-3 text-sm font-bold">{canceled ? "Canceling..." : "Cancel Subscription"}</button>}</div></section>{error && <p role="alert" className="mt-5 text-sm text-[var(--purple-light)]">{error}</p>}<div className="mt-8 grid gap-4 md:grid-cols-3">{plans.map(plan => <article key={plan.name} className={`rounded-2xl border p-6 ${plan.name === currentPlan ? "border-[var(--purple)] bg-[#1d1328]" : "border-[var(--border)] bg-[var(--surface)]"}`}><p className="text-xs font-bold uppercase tracking-wider text-[var(--purple-light)]">{plan.name}</p><p className="mt-5 text-3xl font-bold">{plan.price}<small className="text-sm text-[var(--muted)]"> / month</small></p><p className="mt-4 text-sm text-white">{plan.limit}</p><p className="mt-2 min-h-10 text-sm text-[var(--muted)]">{plan.description}</p><button disabled={!paypalConfigured || plan.name === currentPlan || plan.name === "FREE" || loading !== ""} onClick={() => checkout(plan.name)} className="mt-6 w-full rounded-xl border border-[var(--border)] px-4 py-3 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40">{loading === plan.name ? "Opening PayPal..." : plan.name === currentPlan ? "Current plan" : `Upgrade to ${plan.name}`}</button></article>)}</div></div></main>;
}
