"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { useContent } from "@/components/content-provider";
import { useCreator } from "@/components/creator-provider";
import type { ContentAnalysis, AnalysisCategory, AnalyzerPlatform } from "@/types/analyzer";
import type { ContentItem } from "@/types/content";
import { createClient } from "@/lib/supabase/browser";
import { deleteAnalysis, fetchAnalyses, saveAnalysis, updateAnalysis } from "@/lib/db/analysis-browser";

const platforms: AnalyzerPlatform[] = ["X", "TikTok", "Instagram", "YouTube"];
const keys = ["hook", "clarity", "value", "engagement", "shareability", "cta"] as const;
const labels = { hook: "Hook", clarity: "Clarity", value: "Value", engagement: "Engagement Potential", shareability: "Shareability", cta: "CTA" };

export default function ContentAnalyzer() {
  const params = useSearchParams(); const { items, createContent } = useContent(); const { profile } = useCreator();
  const [content, setContent] = useState(""); const [title, setTitle] = useState(""); const [platform, setPlatform] = useState<AnalyzerPlatform | "">(""); const [contentId, setContentId] = useState<string>();
  const [source, setSource] = useState<"paste" | "library">("paste"); const [analysis, setAnalysis] = useState<ContentAnalysis | null>(null); const [history, setHistory] = useState<ContentAnalysis[]>([]);
  const [loading, setLoading] = useState(false); const [improving, setImproving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [tab, setTab] = useState<"original" | "improved">("original");
  const select = (item: ContentItem) => { setContent(item.body); setTitle(item.title); setPlatform(platforms.includes(item.platform as AnalyzerPlatform) ? item.platform as AnalyzerPlatform : ""); setContentId(item.id); setSource("library"); setAnalysis(null); };
  useEffect(() => { const load = async () => { try { const { data: { user } } = await createClient().auth.getUser(); if (user) setHistory(await fetchAnalyses()); } catch { setHistory([]); } }; void load(); const id = params.get("contentId"); const text = params.get("content"); const item = items.find(row => row.id === id); if (item) select(item); else if (text) { setContent(text); const value = params.get("platform"); if (platforms.includes(value as AnalyzerPlatform)) setPlatform(value as AnalyzerPlatform); } }, [items, params]);
  const persist = (next: ContentAnalysis[]) => { history.filter(item => !next.some(candidate => candidate.id === item.id)).forEach(item => { void deleteAnalysis(item.id); }); setHistory(next); };
  const analyze = async () => { if (!content.trim()) return setError("Paste some content or choose a piece from your library."); if (!platform) return setError("Choose a platform before analyzing."); setLoading(true); setError(""); try { const response = await fetch("/api/ai/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content, title, platform, contentType: "social content", contentId, profile }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setAnalysis(data); setHistory(current => [data, ...current].slice(0, 20)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Contentra couldn't analyze this right now. Try again."); } finally { setLoading(false); } };
  const improve = async () => { if (!analysis) return; setImproving(true); setError(""); try { const response = await fetch("/api/ai/improve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: analysis.content, profile }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const next = { ...analysis, improvedContent: data.content }; setAnalysis(next); if (analysis.id) await updateAnalysis(analysis.id, next); setHistory(current => current.map(item => item.id === next.id ? next : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Contentra couldn't improve this right now. Try again."); } finally { setImproving(false); } };
  const save = async () => { if (!analysis) return; try { const { data: { user } } = await createClient().auth.getUser(); if (!user) throw new Error("Please log in to save analysis."); let id = analysis.contentId; if (!id) id = createContent({ title: analysis.title, body: analysis.content, contentType: "Analyzed content", platform: analysis.platform, status: "DRAFT", tags: [], scheduledAt: null }).id; const next = { ...analysis, contentId: id }; const saved = await saveAnalysis(user.id, next); setAnalysis(saved); setHistory(current => [saved, ...current.filter(item => item.id !== saved.id)].slice(0, 20)); setNotice("Analysis saved to your Content Library."); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn't save this analysis."); } };
  const copy = async () => { if (analysis?.improvedContent) { await navigator.clipboard.writeText(analysis.improvedContent); setNotice("Improved version copied."); } };
  const useVersion = () => { if (analysis?.improvedContent) { setContent(analysis.improvedContent); setTab("improved"); setNotice("Improved version is ready to save or analyze."); } };
  return <main className="min-h-screen bg-[var(--background)] pb-16"><header className="border-b border-[var(--border)] px-5 py-7 sm:px-8"><Link href="/dashboard" className="text-sm text-[var(--purple-light)]">← Dashboard</Link><div className="mx-auto mt-8 max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--purple-light)]">Pre-publish intelligence</p><h1 className="mt-3 text-3xl font-bold sm:text-4xl">Content Analyzer</h1><p className="mt-3 text-base text-[var(--muted)]">Know what works before you hit publish.</p><p className="mt-2 text-sm text-[var(--faint)]">Analyze your hooks, clarity, engagement potential, and calls to action before your content goes live.</p></div></header><div className="mx-auto grid max-w-7xl gap-8 p-5 sm:p-8 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]"><section className="space-y-5"><div className="flex border-b border-[var(--border)]"><button onClick={() => setSource("paste")} className={`border-b-2 px-4 py-3 text-sm font-bold ${source === "paste" ? "border-[var(--purple)] text-white" : "border-transparent text-[var(--muted)]"}`}>Paste Content</button><button onClick={() => setSource("library")} className={`border-b-2 px-4 py-3 text-sm font-bold ${source === "library" ? "border-[var(--purple)] text-white" : "border-transparent text-[var(--muted)]"}`}>From Library</button></div>{source === "library" ? <Library items={items.filter(item => item.status !== "ARCHIVED")} selected={contentId} onSelect={select} /> : <Editor content={content} setContent={value => { setContent(value); setContentId(undefined); setAnalysis(null); }} /> }<div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><label className="text-sm font-bold" htmlFor="platform">Platform</label><select id="platform" value={platform} onChange={event => setPlatform(event.target.value as AnalyzerPlatform)} className="mt-3 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] p-3 text-sm outline-none focus:border-[var(--purple)]"><option value="">Choose a platform</option>{platforms.map(item => <option key={item}>{item}</option>)}</select><button onClick={analyze} disabled={loading} className="mt-5 w-full rounded-xl bg-[var(--purple)] px-5 py-4 text-sm font-bold disabled:opacity-60">{loading ? "Analyzing your content..." : "Analyze Content"}</button>{error && <p role="alert" className="mt-3 text-sm text-[var(--purple-light)]">{error}</p>}{notice && <p role="status" className="mt-3 text-sm text-[var(--muted)]">{notice}</p>}</div><History items={history} open={item => { setAnalysis(item); setContent(item.content); setPlatform(item.platform); setContentId(item.contentId); }} remove={id => persist(history.filter(item => item.id !== id))} /></section><section>{loading ? <Loading /> : analysis ? <Result analysis={analysis} tab={tab} setTab={setTab} improve={improve} improving={improving} copy={copy} save={save} useVersion={useVersion} /> : <Empty />}</section></div></main>;
}
function Editor({ content, setContent }: { content: string; setContent: (value: string) => void }) { return <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><label className="text-sm font-bold" htmlFor="analyzer-content">What are you posting?</label><textarea id="analyzer-content" value={content} onChange={event => setContent(event.target.value)} placeholder="Paste your content here..." rows={15} className="mt-3 w-full resize-y rounded-xl border border-[var(--border)] bg-[var(--background)] p-4 text-sm leading-7 outline-none placeholder:text-[var(--faint)] focus:border-[var(--purple)]" /><div className="mt-3 flex justify-between text-xs text-[var(--muted)]"><span>{content.trim() ? `${content.trim().split(/\s+/).length} words` : ""}</span><span>{content.length.toLocaleString()} characters</span></div></div> }
function Library({ items, selected, onSelect }: { items: ContentItem[]; selected?: string; onSelect: (item: ContentItem) => void }) { return <div className="space-y-3">{items.length ? items.map(item => <button key={item.id} onClick={() => onSelect(item)} className={`block w-full rounded-2xl border p-5 text-left ${selected === item.id ? "border-[var(--purple)] bg-[#1d1328]" : "border-[var(--border)] bg-[var(--surface)]"}`}><span className="text-xs font-bold uppercase tracking-wider text-[var(--purple-light)]">{item.platform}</span><h2 className="mt-3 font-bold">{item.title || "Untitled content"}</h2><p className="mt-2 line-clamp-2 text-sm text-[var(--muted)]">{item.body}</p></button>) : <p className="rounded-2xl border border-dashed border-[var(--border)] p-7 text-center text-sm text-[var(--muted)]">Your Content Library is empty.</p>}</div> }
function Loading() { return <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><p className="animate-pulse font-bold text-[var(--purple-light)]">Analyzing your content...</p><div className="mt-6 space-y-4">{keys.map(key => <div key={key} className="h-8 animate-pulse rounded bg-[#281640]" />)}</div></div> }
function Empty() { return <div className="flex min-h-[420px] flex-col items-center justify-center rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface)] p-8 text-center"><div className="text-3xl text-[var(--purple-light)]">✦</div><h2 className="mt-6 text-xl font-bold">Ready to improve your content?</h2><p className="mt-3 text-sm text-[var(--muted)]">Paste a post or choose something from your Content Library.</p></div> }
function Result({ analysis, tab, setTab, improve, improving, copy, save, useVersion }: { analysis: ContentAnalysis; tab: "original" | "improved"; setTab: (value: "original" | "improved") => void; improve: () => void; improving: boolean; copy: () => void; save: () => void; useVersion: () => void }) { return <div className="space-y-5"><div className="rounded-2xl border border-[#4c2b73] bg-[var(--surface)] p-6"><p className="text-xs font-bold uppercase tracking-wider text-[var(--purple-light)]">Content Score</p><div className="mt-2 text-6xl font-bold">{analysis.overallScore}<span className="text-2xl text-[var(--muted)]"> / 100</span></div><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-3">{keys.map(key => <div key={key} className="rounded-xl border border-[var(--border)] bg-[var(--background)] p-3"><p className="text-xs text-[var(--muted)]">{labels[key]}</p><p className="mt-1 text-xl font-bold text-[var(--purple-light)]">{analysis[key].score}</p></div>)}</div></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold">{tab === "improved" ? "Improved Version" : "Original Content"}</h2>{analysis.improvedContent && <div className="flex gap-1"><button onClick={() => setTab("original")} className="rounded bg-[var(--background)] px-3 py-2 text-xs font-bold">Original</button><button onClick={() => setTab("improved")} className="rounded bg-[var(--purple-dark)] px-3 py-2 text-xs font-bold">Improved</button></div>}</div><p className="mt-5 whitespace-pre-wrap text-sm leading-7">{tab === "improved" && analysis.improvedContent ? analysis.improvedContent : analysis.content}</p></div><div className="grid gap-4 sm:grid-cols-2">{keys.map(key => <Category key={key} label={labels[key]} data={analysis[key]} />)}</div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><h2 className="font-bold">What&apos;s Working</h2><List items={analysis.strengths} /><h2 className="mt-6 font-bold">What To Improve</h2><List items={analysis.recommendations} numbered /></div><div className="grid gap-2 sm:grid-cols-2"><button onClick={improve} disabled={improving || Boolean(analysis.improvedContent)} className="rounded-xl bg-[var(--purple)] px-4 py-3 text-sm font-bold">{improving ? "Improving content..." : "Improve Content"}</button><button onClick={copy} disabled={!analysis.improvedContent} className="rounded-xl border border-[var(--border)] px-4 py-3 text-sm font-bold disabled:opacity-40">Copy improved</button><button onClick={useVersion} disabled={!analysis.improvedContent} className="rounded-xl border border-[var(--border)] px-4 py-3 text-sm font-bold disabled:opacity-40">Use This Version</button><button onClick={save} className="rounded-xl border border-[var(--border)] px-4 py-3 text-sm font-bold">Save Analysis</button></div></div> }
function Category({ label, data }: { label: string; data: AnalysisCategory }) { return <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex justify-between gap-3"><h3 className="font-bold">{label}</h3><b className="text-xl text-[var(--purple-light)]">{data.score}<small className="text-xs text-[var(--muted)]"> / 100</small></b></div><List title="What's working" items={data.strengths} /><List title="What could improve" items={data.weaknesses} /><List title="Recommendation" items={data.recommendations} /></article> }
function List({ title, items, numbered }: { title?: string; items: string[]; numbered?: boolean }) { return <div className="mt-4">{title && <h4 className="mb-2 text-xs font-bold uppercase tracking-wider text-[var(--muted)]">{title}</h4>}<ol className={numbered ? "list-decimal space-y-2 pl-5" : "space-y-2"}>{items.length ? items.map((item, index) => <li key={`${item}-${index}`} className="text-sm leading-6 text-[var(--muted)]">{!numbered && <span className="mr-2 text-[var(--purple-light)]">✓</span>}{item}</li>) : <li className="list-none text-sm text-[var(--faint)]">No details returned.</li>}</ol></div> }
function History({ items, open, remove }: { items: ContentAnalysis[]; open: (item: ContentAnalysis) => void; remove: (id: string) => void }) { return <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex justify-between"><h2 className="font-bold">Recent Analyses</h2><span className="text-xs text-[var(--faint)]">{items.length} saved</span></div>{items.length ? <div className="mt-4 space-y-2">{items.slice(0, 5).map(item => <div key={item.id} className="flex justify-between gap-3 rounded-xl border border-[var(--border)] p-3"><button onClick={() => open(item)} className="min-w-0 text-left"><p className="truncate text-sm font-bold">{item.title}</p><p className="mt-1 text-xs text-[var(--muted)]">{item.platform} · {item.overallScore} / 100</p></button><button onClick={() => remove(item.id)} className="text-xs text-[var(--muted)]">Delete</button></div>)}</div> : <p className="mt-4 text-sm text-[var(--muted)]">Your saved analyses will appear here.</p>}</section> }
